### ISSUE TITLE
Links don't work in communities

### ISSUE THREAD

**Issue by Sand-Piper** [ForceDotComLabs/EnhancedLightningGrid#3]
There is an issue with the links in Lightning Communities.  The link in question is often the "Name" field.  For example, when displaying a list of Contacts, the Contact Name column will contain a link to each Contact.

The issue appears to be that the links don't use the "e.force:navigateToSObject" event.  They seem to just be url links which don't go to the correct location or even the correct community.

An example link endpoint is "https://mycommunities.force.com/003000000XXXXxxXXX".  This not only lacks the community prefix (https://mycommunities.force.com/**partners**/003000000XXXXxxXXX
), but it can not work in Lightning Communities.

![capture](https://user-images.githubusercontent.com/33075738/40959081-f4905c38-68de-11e8-864e-724e6ee32211.PNG)

**Comment by dylangold** [comment]
@Sand-Piper I've found that this works correctly after installing the unmanaged package from github, but not the managed one in the appexchange. As the appexchange version hasn't been updated since January, it looks like this is fixed, but the managed version isn't updated yet.

**Comment by MDalt** [comment]
@dylangold Can you point to the unmanaged package here? I don't see it and need this fix.

**Comment by tbeary-agleader** [comment]
Links in Lightning Communities are still broken as of the Sept 2018 release on the AppExchange. Is it possible to install the unmanaged package from github, can you please point to it?

**Comment by NikVerse** [comment]
Did below workaround on 9th October 2019 to resolve the issue for now, as still the repository is not updated to have this issue fixed:

In sdgDatagridCell.cmp
![image](https://user-images.githubusercontent.com/14296064/66452361-ec85a700-eaab-11e9-903c-74cd9b1e75ea.png)

In sdgDatagridCellHelper.js
![image](https://user-images.githubusercontent.com/14296064/66452265-90bb1e00-eaab-11e9-9070-7968c11b147f.png)

In sdg.cmp
![image](https://user-images.githubusercontent.com/14296064/66452345-dbd53100-eaab-11e9-831e-395b985107bf.png)

![image](https://user-images.githubusercontent.com/14296064/66452319-c7913400-eaab-11e9-9d45-dcb71bc7008e.png)

Thanks
